### PR TITLE
Add VSphere CPI support for deploying BOSH

### PR DESCRIPTION
**Pull request by sneal**
This deploys BOSH to a vSphere 6.0 instance. Additionally it supports a configurable subnet.

Note - I modified how the bosh-init dependency is vendored. I forked bosh-init and fixed its vendoring and pointed omg-cli at my fork.

```
$ omg-cli vsphere --bosh-private-ip 172.16.0.81 --vsphere-address 172.16.1.2 --vsphere-user "vsphereadmin" --vsphere-password "secret" --vsphere-datacenter-name PCF --vsphere-vm-folder pcf_vms --vsphere-template-folder pcf_templates --vsphere-datastore-pattern PCF_STORAGE_2 --vsphere-persistent-datastore-pattern PCF_STORAGE_1 --vsphere-disk-path pcf_disk --vsphere-clusters PCF_CLUSTER_1 --vsphere-subnet1-name "PCF_Net" --vsphere-subnet1-range "172.16.0.0/23" --vsphere-subnet1-gateway 172.16.0.1 --vsphere-subnet1-dns 172.16.1.2
deploying your bosh
Deployment manifest: '/var/folders/55/jdzf57vn62j1qhrpzxm1w7tm0000gn/T/bosh-init-deployment539002396'
Deployment state: '/var/folders/55/jdzf57vn62j1qhrpzxm1w7tm0000gn/T/bosh-init-deployment539002396-state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bosh-vsphere-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:00)
Finished validating (00:00:01)

Started installing CPI
  Compiling package 'vsphere_cpi_mkisofs/b3ebe039dae6a312784ece4da34d66053d1dfbba'... Finished (00:03:07)
  Compiling package 'vsphere_cpi_ruby/b11a9d73a466e071628d38912aecd41016434906'... Finished (00:01:55)
  Compiling package 'vsphere_cpi/05edd5affc9b96f1dc66388b1ec9c4a5068cb30b'... Finished (00:00:52)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:05:56)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3232.4'... Finished (00:06:51)

Started deploying
  Creating VM for instance 'bosh/0' from stemcell 'sc-ddc45b25-fe48-4b90-bce3-6e5deaaf708e'... Finished (00:00:16)
  Waiting for the agent on VM 'vm-7a9580af-1a57-4c9b-89a0-66980031da3e' to be ready... Finished (00:00:29)
  Creating disk... Finished (00:00:05)
  Attaching disk 'disk-c0b9c8af-d1d2-4e52-93ed-fcb805a38c65' to VM 'vm-7a9580af-1a57-4c9b-89a0-66980031da3e'... Finished (00:00:18)
  Rendering job templates... Finished (00:00:07)
  Compiling package 'ruby/030e3d4eafd00b10bbfa879bcf44fba62139205e'... Finished (00:02:16)
  Compiling package 'vsphere_cpi_ruby/b11a9d73a466e071628d38912aecd41016434906'... Finished (00:02:26)
  Compiling package 'genisoimage/008d332ba1471bccf9d9aeb64c258fdd4bf76201'... Finished (00:00:19)
  Compiling package 'vsphere_cpi_mkisofs/b3ebe039dae6a312784ece4da34d66053d1dfbba'... Finished (00:02:47)
  Compiling package 'nginx/1d356bbd17ed8c349fd1053093222d78559687ec'... Finished (00:00:42)
  Compiling package 'mysql/b7e73acc0bfe05f1c6cbfd97bf92d39b0d3155d5'... Finished (00:00:29)
  Compiling package 's3cli/46a8902dea5b853b9cc2a8ff570503d0201c4f4f'... Finished (00:00:03)
  Compiling package 'postgres/55dbf1828bbb8e5fcd7dc7550cfb73de89312458'... Finished (00:03:04)
  Compiling package 'libpq/09c8f60b87c9bd41b37b0f62159c9d77163f52b8'... Finished (00:00:32)
  Compiling package 'health_monitor/4c4f257a58778faf38d38d71516f95a002846e34'... Finished (00:01:13)
  Compiling package 'nats/6a31c7bb0d5ffa2a9f43c7fd7193193438e20e92'... Finished (00:00:10)
  Compiling package 'registry/d1050b6bb9fba2444aa8d0b36361e5a47a702f3d'... Finished (00:01:28)
  Compiling package 'director/099c19f03d39e0aca6a28b336f50da4952b70cdc'... Finished (00:01:45)
  Compiling package 'vsphere_cpi/05edd5affc9b96f1dc66388b1ec9c4a5068cb30b'... Finished (00:01:04)
  Updating instance 'bosh/0'... Finished (00:00:23)
  Waiting for instance 'bosh/0' to be running... Finished (00:00:11)
  Running the post-start scripts 'bosh/0'... Finished (00:00:00)
Finished deploying (00:20:18)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)
```

### CODE REVIEW

**Comment by xchapter7x** [comment]
can you add some tests before we merge this?

**Comment by sneal** [comment]
@xchapter7x Added tests, added more types, added persistent data store fallback.

**Comment by xchapter7x** [comment]
@sneal also this build is broken in wercker... just added you to the app
https://app.wercker.com/#applications/573fd97b4933d8d127331da3


seems like your bosh-init fork cant be pulled

**Comment by sneal** [comment]
@xchapter7x build fixed. You can't clone a repo using SSH via glide from wercker, so I switched it to use https.

**Pull request closed without merging**
